# Generated by Django 4.1.7 on 2023-03-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_price_alter_restaurant_cash_balance'),
        ('users', '0003_purchase_history_delete_purchasehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_History',
            new_name='PurchaseHistory',
        ),
    ]
