# Generated by Django 4.1.7 on 2023-03-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_delete_user_alter_purchasehistory_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customer',
        ),
    ]
