# Generated by Django 4.1.7 on 2023-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_users_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
