# Generated by Django 4.1.7 on 2023-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_dish_name_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
